spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 583838208893-nkcg6llf72stmd0la8o93n4bohgbfch6.apps.googleusercontent.com
            client-secret: ${clientSecret}
            clientAuthenticationScheme: form
            scope: openid,profile,email
            accessTokenUri: https://www.googleapis.com/oauth2/v4/token
            userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
          resource:
            userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
            preferTokenInfo: true
# ...